import {tracdap as trac} from "@finos/tracdap-web-api";
import {UiAttributesListRow} from "../../../../types/types_attributes_and_parameters";

export const uiAttributesListAttrs: trac.metadata.ITagUpdate[] = [
    {
        attrName: "key", value: {stringValue: "ui_attributes_list"}
    },
    {
        attrName: "name", value: {stringValue: "Metadata attributes list"}
    },
    {
        attrName: "description",
        value: {
            stringValue: "There is often a need to tag objects in TRAC such as data, models or files with additional metadata to help users understand each item better. In some cases this is required to enable the user interface to function, for example flagging whether a dataset can be found in search results. This dataset defines a set of attributes that can be added to an object's metadata. Although the tag system is deliberately open ended it is better to define all of the tags in use in this dataset and document what each does."
        }
    },
    {
        attrName: "show_in_search_results", value: {booleanValue: false}
    }
]

export const uiAttributesListSchema: trac.metadata.IFieldSchema[] = [
    {
        fieldName: "OBJECT_TYPES",
        label: "Object types attribute can be added to",
        fieldType: trac.STRING,
        fieldOrder: 0,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "ID",
        label: "ID",
        fieldType: trac.STRING,
        fieldOrder: 1,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "NAME",
        label: "Name",
        fieldType: trac.STRING,
        fieldOrder: 2,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "DESCRIPTION",
        label: "Description",
        fieldType: trac.STRING,
        fieldOrder: 3,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "CATEGORY",
        label: "Category",
        fieldType: trac.STRING,
        fieldOrder: 4,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "TOOLTIP",
        label: "Tooltip",
        fieldType: trac.STRING,
        fieldOrder: 5,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "HIDDEN",
        label: "Hidden",
        fieldType: trac.BOOLEAN,
        fieldOrder: 6,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "LINKED_TO_ID",
        label: "Show this attribute based on another attribute's value",
        fieldType: trac.STRING,
        fieldOrder: 7,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "LINKED_TO_VALUE",
        label: "Linked attribute's value required to show this attribute",
        fieldType: trac.STRING,
        fieldOrder: 8,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "BASIC_TYPE",
        label: "Attribute type",
        fieldType: trac.INTEGER,
        fieldOrder: 9,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "DEFAULT_VALUE",
        label: "Default value",
        fieldType: trac.STRING,
        fieldOrder: 10,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "FORMAT_CODE",
        label: "Attribute format code",
        fieldType: trac.STRING,
        fieldOrder: 11,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "MINIMUM_VALUE",
        label: "Minimum value or length",
        fieldType: trac.STRING,
        fieldOrder: 12,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "MAXIMUM_VALUE",
        label: "Maximum value or length",
        fieldType: trac.STRING,
        fieldOrder: 13,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "USE_OPTIONS",
        label: "User must select from a range of options",
        fieldType: trac.BOOLEAN,
        fieldOrder: 14,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "OPTIONS_INCREMENT",
        label: "Increment when shown as an option",
        fieldType: trac.STRING,
        fieldOrder: 15,
        categorical: true,
        businessKey: false
    },
    {
        fieldName: "OPTIONS_VALUES",
        label: "Option values",
        fieldType: trac.STRING,
        fieldOrder: 16,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "OPTIONS_LABELS",
        label: "Option labels",
        fieldType: trac.STRING,
        fieldOrder: 17,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "IS_MULTI",
        label: "Allow multiple options to be selected",
        fieldType: trac.BOOLEAN,
        fieldOrder: 18,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "MUST_VALIDATE",
        label: "User set values must validate before saving",
        fieldType: trac.BOOLEAN,
        fieldOrder: 19,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "RESERVED_FOR_APPLICATION",
        label: "Whether the user can edit the attribute",
        fieldType: trac.BOOLEAN,
        fieldOrder: 20,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "NUMBER_OF_ROWS",
        label: "Number of rows for text areas",
        fieldType: trac.INTEGER,
        fieldOrder: 21,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "WIDTH_MULTIPLIER",
        label: "Width on screen",
        fieldType: trac.INTEGER,
        fieldOrder: 22,
        categorical: false,
        businessKey: false
    },
    {
        fieldName: "SET_AUTOMATICALLY_BY_APPLICATION",
        label: "Is the attribute set by the application rather than by the user",
        fieldType: trac.BOOLEAN,
        fieldOrder: 23,
        categorical: false,
        businessKey: false
    }
]

export const defaultUiAttributesList: UiAttributesListRow[] = [
    {
        "OBJECT_TYPES": "DATA||FLOW||MODEL||SCHEMA||FILE||CUSTOM",
        "ID": "key",
        "NAME": "Key",
        "DESCRIPTION": "A camelCase or snake_case key for the %object%. This is used when searching for items, for example to match the datasets and models to those needed in a flow.",
        "CATEGORY": "GENERAL",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": "5",
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "MUST_VALIDATE": true,
        "RESERVED_FOR_APPLICATION": true,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": false
    },
    {
        "OBJECT_TYPES": "ALL",
        "ID": "name",
        "NAME": "Name",
        "DESCRIPTION": "A name for the %object%, this should be short and reflect what the %object% contains.",
        "CATEGORY": "GENERAL",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": "5",
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "MUST_VALIDATE": true,
        "RESERVED_FOR_APPLICATION": true,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 2,
        "SET_AUTOMATICALLY_BY_APPLICATION": false
    },
    {
        "OBJECT_TYPES": "ALL",
        "ID": "description",
        "NAME": "Description",
        "DESCRIPTION": "A description for the %object%, this should contain detailed information about this item so that it can be differentiated from other similar %object%s.",
        "CATEGORY": "GENERAL",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "MUST_VALIDATE": true,
        "RESERVED_FOR_APPLICATION": true,
        "NUMBER_OF_ROWS": 3,
        "WIDTH_MULTIPLIER": 3,
        "SET_AUTOMATICALLY_BY_APPLICATION": false
    },
    {
        "OBJECT_TYPES": "DATA||FLOW||SCHEMA||MODEL",
        "ID": "import_method",
        "NAME": "Import method",
        "DESCRIPTION": "This how the object was loaded into TRAC.",
        "CATEGORY": "LOCAL_FILE_DETAILS",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": true,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": "user_interface||batch",
        "OPTIONS_LABELS": "User interface||Batch",
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "DATA||FLOW||SCHEMA",
        "ID": "original_file_name",
        "NAME": "Original file name",
        "DESCRIPTION": "This is the filename of local data (csv or xlsx), flow (json) or schema (csv) files that have been loaded.",
        "CATEGORY": "LOCAL_FILE_DETAILS",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "DATA||FLOW||SCHEMA",
        "ID": "original_file_size",
        "NAME": "Original file size",
        "DESCRIPTION": "This is the size of local data (csv or xlsx), flow (json) or schema (csv) files that have been loaded.",
        "CATEGORY": "LOCAL_FILE_DETAILS",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.INTEGER,
        "FORMAT_CODE": ",|.|0||",
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "DATA",
        "ID": "number_of_rows",
        "NAME": "Number of rows in dataset",
        "DESCRIPTION": "The number of rows in the data.",
        "CATEGORY": "LOCAL_FILE_DETAILS",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.INTEGER,
        "FORMAT_CODE": ",|.|0|||1",
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "DATA",
        "ID": "duration_of_load",
        "NAME": "Duration of data load (milliseconds)",
        "DESCRIPTION": "This is the time it took to load the data via the user interface.",
        "CATEGORY": "LOCAL_FILE_DETAILS",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.INTEGER,
        "FORMAT_CODE": ",|.|0|||1",
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "DATA||FLOW||SCHEMA",
        "ID": "original_file_modified_date",
        "NAME": "Original file modified date",
        "DESCRIPTION": "This is the modified date of local data (csv or xlsx), flow (json) or schema (csv) files that have been loaded.",
        "CATEGORY": "LOCAL_FILE_DETAILS",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.DATETIME,
        "FORMAT_CODE": "DATETIME",
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "SCHEMA",
        "ID": "number_of_fields",
        "NAME": "Number of fields in the schema",
        "DESCRIPTION": "The number of fields in a schema",
        "CATEGORY": "GENERAL",
        "TOOLTIP": null,
        "HIDDEN": true,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.INTEGER,
        "FORMAT_CODE": ",|.|0||",
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "ALL",
        "ID": "show_in_search_results",
        "NAME": "Show in search results",
        "DESCRIPTION": "Whether the %object% should show in the any of the drop down lists and be available to select.",
        "CATEGORY": "GENERAL",
        "TOOLTIP": "This is usually set to false where there has been an issue identified with the %object% and you want to prevent users from selecting it. For example a dataset with the wrong data has been loaded.",
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": "TRUE",
        "BASIC_TYPE": trac.BOOLEAN,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": false
    },
    {
        "OBJECT_TYPES": "JOB",
        "ID": "job_tag",
        "NAME": "Tag",
        "DESCRIPTION": "This information will be tagged to all the outputs of this job, allowing you to identify which datasets it created.",
        "CATEGORY": "GENERAL",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.BasicType.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": false,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": null,
        "OPTIONS_LABELS": null,
        "IS_MULTI": false,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": false
    },
    {
        "OBJECT_TYPES": "ALL",
        "ID": "business_segments",
        "NAME": "Business segments",
        "DESCRIPTION": "Items can be tagged with related business terms to help find and organize them.",
        "CATEGORY": "CATEGORY",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": true,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": "DEFAULT",
        "OPTIONS_LABELS": "DEFAULT",
        "IS_MULTI": true,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 2,
        "SET_AUTOMATICALLY_BY_APPLICATION": false
    },
    {
        "OBJECT_TYPES": "FILE",
        "ID": "attached_object",
        "NAME": "Attached object",
        "DESCRIPTION": "When you upload a file and attach it to an model or dataset then this is a reference to the items attached to it.",
        "CATEGORY": "CATEGORY",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": true,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": "DUMMY",
        "OPTIONS_LABELS": "Dummy",
        "IS_MULTI": true,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 1,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    },
    {
        "OBJECT_TYPES": "DATA",
        "ID": "hidden_columns",
        "NAME": "Hidden columns",
        "DESCRIPTION": "Which columns to hide when the dataset is viewed in a table. Users will still be able to change the visibility of these columns.",
        "CATEGORY": "VISUALISATION",
        "TOOLTIP": null,
        "HIDDEN": false,
        "LINKED_TO_ID": null,
        "LINKED_TO_VALUE": null,
        "DEFAULT_VALUE": null,
        "BASIC_TYPE": trac.STRING,
        "FORMAT_CODE": null,
        "MINIMUM_VALUE": null,
        "MAXIMUM_VALUE": null,
        "USE_OPTIONS": true,
        "OPTIONS_INCREMENT": null,
        "OPTIONS_VALUES": "USE_SCHEMA",
        "OPTIONS_LABELS": "USE_SCHEMA",
        "IS_MULTI": true,
        "RESERVED_FOR_APPLICATION": true,
        "MUST_VALIDATE": false,
        "NUMBER_OF_ROWS": 1,
        "WIDTH_MULTIPLIER": 2,
        "SET_AUTOMATICALLY_BY_APPLICATION": true
    }
]