
nodes:

  customer_loans:
    nodeType: "INPUT_NODE"

  customer_data_filter:
    nodeType: "MODEL_NODE"
    inputs: [customer_loans]
    outputs: [filtered_loans]

  pnl_aggregation:
    nodeType: "MODEL_NODE"
    inputs: [customer_loans]
    outputs: [profit_by_region]

  profit_by_region:
    nodeType: "OUTPUT_NODE"


edges:

  - source: { node: customer_data_filter, socket: filtered_loans }
    target: { node: pnl_aggregation, socket: customer_loans }
