
nodes:

  unfiltered_loans:
    nodeType: "INPUT_NODE"

  customer_data_filter:
    nodeType: "MODEL_NODE"
    inputs: [unfiltered_loans]
    outputs: [customer_loans]

  pnl_aggregation:
    nodeType: "MODEL_NODE"
    inputs: [customer_loans]
    outputs: [profit_by_region]

  profit_by_region:
    nodeType: "OUTPUT_NODE"
