job:
  exportData:

    placements:

      profit_by_region_csv:
        dataId: { path: outputs/using_data/profit_by_region.csv, schema: schemas/profit_by_region.csv }
        location: { storageKey: exported_data, storagePath: data_export/profit_by_region.csv }

      profit_by_region_parquet:
        dataId: { path: outputs/using_data/profit_by_region.csv, schema: schemas/profit_by_region.csv }
        location: { storageKey: exported_data, storagePath: data_export/profit_by_region.parquet }

      profit_by_region_arrow:
        dataId: { path: outputs/using_data/profit_by_region.csv, schema: schemas/profit_by_region.csv }
        location: { storageKey: exported_data, storagePath: data_export/profit_by_region.arrow }
