
job:
  runModel:

    parameters:
      filter_column: region
      filter_value: ulster

    inputs:
      # Dynamic inputs for local jobs need a file format with schema information
      original_data: "inputs/loan_final313_100.parquet"

    outputs:
      filtered_data: "outputs/dynamic_io/filtered_data.csv"
