job:
  runFlow:

    flow: ./flow_export_flow.yaml

    parameters:
      eur_usd_rate: 1.2071
      default_weighting: 1.5
      filter_defaults: false
      storage_key: exported_data
      export_comment: "Exporting some example data from a flow"

    inputs:
      customer_loans: "inputs/loan_final313_100.csv"

    outputs:
      profit_by_region: "outputs/flow_export/profit_by_region.csv"

    models:
      pnl_aggregation: tutorial.using_data.PnlAggregation
      data_export: tutorial.data_export.DataExportExample

    exportStorageAccess:
      - exported_data
