

job:
  jobGroup:
    sequential:
      jobs:

        - importData:

            model: tutorial.data_import.SimpleDataImport

            parameters:
              storage_key: staging_data
              source_file: sample_data.parquet

            outputs:
              customer_loans: primary/data_import/customer_loans.csv

            storageAccess:
              - staging_data

        - runModel:

            model: tutorial.using_data.PnlAggregation

            parameters:
              eur_usd_rate: 1.2071
              default_weighting: 1.5
              filter_defaults: false

            inputs:
              customer_loans: primary/data_import/customer_loans.csv

            outputs:
              profit_by_region: generated/using_data/profit_by_region.csv

        - exportData:

            placements:
              profit_by_region:
                dataId: { path: generated/using_data/profit_by_region.csv, schema: schemas/profit_by_region.csv }
                location: { storageKey: exported_data, storagePath: job_group/profit_by_region.csv }
