

sequential:

  - job:
      runModel:

        parameters:
          eur_usd_rate: 1.2071
          default_weighting: 1.5
          filter_defaults: false

        inputs:
          customer_loans: "inputs/loan_final313_100.csv"

        outputs:
          profit_by_region: "outputs/optional_io/profit_by_region.csv"

  - job:
      exportData:

        exportType: JOB_OUTPUTS

        exports:
          - selector: trac_prior_job

        targetLocation: risk_dw


  - job:
      exportData:

        exportType: DATA

        exports:
          - selector: "outputs/optional_io/profit_by_region.csv"
            data_key: profit_by_region
            version: latest

          - selector: "outputs/optional_io/exclusions.csv"
            data_key: exclusions
            version: latest

        targetLocation: risk_dw
