
job:
  runModel:

    parameters:
      eur_usd_rate: 1.2071
      default_weighting: 1.5
      filter_defaults: false

    inputs:
      customer_loans: "inputs/loan_final313_100.csv"
      account_filter: "inputs/account_filter.csv"

    outputs:
      profit_by_region: "outputs/optional_io/profit_by_region.csv"
      exclusions: "outputs/optional_io/exclusions.csv"
