
job:
  runModel:

    parameters:
      eur_usd_rate: 1.2071

    inputs:
      customer_loans: "inputs/quick_start_input.csv"

    outputs:
      profit_by_region: "outputs/quick_start/quick_start_output.csv"
