
job:
  runModel:

    parameters:
      eur_usd_rate: 1.2071

    inputs:
      quick_start_input: "inputs/quick_start_input.csv"

    outputs:
      quick_start_output: "outputs/quick_start/quick_start_output.csv"
