

job:
  runModel:

    parameters:

    inputs:
      customer_loans: "inputs/loan_final313_100.csv"
      account_filter: "inputs/account_filter.csv"

    outputs:
      data_report: "outputs/runtime_metadata/data_report.md"
