

properties:

  storage.default.location: example_data
  storage.default.format: CSV


resources:

  example_data:
    resourceType: INTERNAL_STORAGE
    protocol: LOCAL
    properties:
      rootPath: ../data

  staging_data:
    resourceType: EXTERNAL_STORAGE
    protocol: LOCAL
    properties:
      rootPath: ../data/inputs/staging

  exported_data:
    resourceType: EXTERNAL_STORAGE
    protocol: LOCAL
    properties:
      rootPath: ../data/exports
