
storage:

  defaultBucket: example_data
  defaultFormat: CSV

  buckets:

    example_data:
      protocol: LOCAL
      properties:
        rootPath: ../data


sparkSettings:

  sparkProps:
    spark.cores.max: 4
    spark.driver.memory: 2G
    spark.executor.memory: 2G
    spark.default.parallelism: 8
    spark.sql.shuffle.partitions: 8
