# Copyright 2022 Accenture Global Solutions Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config:
  secret.type: PKCS12
  secret.url: secrets.p12


platformInfo:
  environment: TEST_ENVIRONMENT
  production: false
  deploymentInfo:
    region: UK


authentication:
  jwtIssuer: http://localhost/
  jwtExpiry: 7200
  provider:
    protocol: guest
    properties:
      userId: guest
      userName: Guest User


# Stick with H2 database for storage integration testing
metadata:
  format: PROTO
  database:
    protocol: JDBC
    properties:
      dialect: H2
      jdbcUrl: ${TRAC_DIR}/trac.meta
      h2.user: trac
      h2.pass: trac
      h2.schema: public
      pool.size: 10
      pool.overflow: 5


storage:

  defaultBucket: STORAGE_INTEGRATION
  defaultFormat: ARROW_FILE

  buckets:

    STORAGE_INTEGRATION:
      protocol: GCS
      properties:
        region: ${TRAC_GCP_REGION}
        project: ${TRAC_GCP_PROJECT}
        bucket: ${TRAC_GCP_BUCKET}
        prefix: int_storage_${TRAC_TEST_ID}/


repositories:
  UNIT_TEST_REPO:
    protocol: git
    properties:
      repoUrl: ${CURRENT_GIT_ORIGIN}


executor:
  protocol: LOCAL
  properties:
    venvPath: ${TRAC_EXEC_DIR}/venv


jobCache:
  protocol: LOCAL


services:

  metadata:
    port: 8081

  data:
    port: 8082

  orchestrator:
    port: 8083

deployment:
  layout: SANDBOX
