
properties:
  storage.default.location: NOT_USED

resources:

  data_integration:
    resourceType: EXTERNAL_STORAGE
    protocol: SQL
    properties:
      dialect: POSTGRESQL
      driver.python: alchemy
      alchemy.url: postgresql+pg8000://metadb:5432/trac
      alchemy.username: trac_admin
      alchemy.password: DB_SECRET
