
# Test resources for tenant 2 SOME_OTHER_CORP

resourceClass: trac_resources

resources:

  UNIT_TEST_STORAGE:
    resourceType: INTERNAL_STORAGE
    protocol: LOCAL
    publicProperties:
      unit_test_property: storage_value_1
      unit-test.property: storage-value.1
    secrets:
      rootPath: ${TRAC_STORAGE_DIR}
