
# Use secrets for required properties
# Test that secrets in dynamic config get to where they are needed

tenants:
  ACME_CORP:

    displayName: ACME Projectiles Inc.

    properties:
      storage.default.location: UNIT_TEST_STORAGE
      storage.default.format: ARROW_FILE
      storage.default.layout: OBJECT_ID_LAYOUT

  SOME_OTHER_CORP:

    displayName: Replica Projectiles Inc.

    properties:
      storage.defaults.location: UNIT_TEST_STORAGE
