
tenants:

  ACME_CORP:

    properties:
      tenant.displayName: ACME Industrial Supplies Inc.
      storage.default.location: STORAGE1
      storage.default.format: ARROW_FILE
      storage.default.layout: OBJECT_ID_LAYOUT

    resources:

      STORAGE1:
        resourceType: INTERNAL_STORAGE
        protocol: LOCAL
        properties:
          rootPath: ./build/run

      # Add your own repositories in here to load models into TRAC
      example_repo:
        resourceType: MODEL_REPOSITORY
        protocol: git
        properties:
          repoUrl: https://github.com/finos/tracdap
