/**
 * A component that shows a summary of a particular version of a schema stored in TRAC. This component is for viewing
 * in a PDF, there is a sister component called {@link SchemaViewer}  that is for viewing in a browser. These two
 * components need to be kept in sync so if a change is made to one then it should be reflected in the other.
 *
 * @module SchemaViewerPdf
 * @category Component
 */

import {convertDateObjectToFormatCode} from "../../utils/utils_formats";
import {MetadataViewerPdf} from "./MetadataViewerPdf";
import type {Option} from "../../../types/types_general";
import {PdfCss} from "../../../config/config_pdf_css";
import PropTypes from "prop-types";
import React from "react";
import {SchemaFieldsTablePdf} from "./SchemaFieldsTablePdf";
import {StyleSheet, Text, View} from "@react-pdf/renderer";
import {tracdap as trac} from "@finos/tracdap-web-api";
import type {UiAttributesProps} from "../../../types/types_attributes_and_parameters";

/**
 * An interface for the props of the SchemaViewerPdf component.
 */
export interface Props {

    /**
     * The attribute data from the {@link setAttributesStore}, this is used to augment the presentation
     * of the attribute table with formats and the correct names.
     */
    allProcessedAttributes: Record<string, UiAttributesProps>
    /**
     * The metadata for the object to create a PDF report on.
     */
    tag: trac.metadata.ITag
    /**
     * The tenant option that the user is working under.
     */
    tenant: Option<string>
    /**
     * The username of the person using the application.
     */
    userName: string
    /**
     * The user ID of the person using the application.
     */
    userId: string
}

export const SchemaViewerPdf = (props: Props) => {

    const {allProcessedAttributes, tag, tenant, userName, userId} = props

    // Create the css styles for the exported PDF element
    const styles = StyleSheet.create(PdfCss)

    return (
        <React.Fragment>
            <View>
                <Text style={styles.title}>Schema governance report</Text>

                <Text style={styles.text}>
                    {`This document is a summary of a schema held in the TRAC application and was downloaded by ${userName} (${userId}) on ${convertDateObjectToFormatCode(new Date(), "DATETIME")}. The schema is stored under the ${tenant.label} (${tenant.value}) tenant.`}
                </Text>
            </View>

            <View style={styles.section}>
                <Text>1. Metadata</Text>
            </View>

            <Text style={styles.text}>
                The table below shows the metadata for the schema. The header contains the dataset&apos;s unique ID and
                version numbers. The attributes are tags attached to the object, these are either automatically
                generated by TRAC (e.g. who loaded it) or manually added by users.
            </Text>

            <MetadataViewerPdf metadata={tag} allProcessedAttributes={allProcessedAttributes}/>

            <View wrap={false}>
                <View style={styles.section}>
                    <Text>2. Schema</Text>
                </View>
                <SchemaFieldsTablePdf schema={tag?.definition?.schema?.table?.fields}/>
            </View>

        </React.Fragment>
    )
};

SchemaViewerPdf.propTypes = {

    allProcessedAttributes: PropTypes.object,
    tag: PropTypes.object.isRequired,
    tenant: PropTypes.object.isRequired,
    userName: PropTypes.string.isRequired,
    userId: PropTypes.string.isRequired
};