name: Packaging

on:

  # Build packages for pull requests, to make sure there are no packaging issues
  pull_request:

  # Re-run packaging jobs in main, to make sure there are no issues from the merge
  push:
    branches:
      - main

  # Build packages when releases are published on GitHub
  # Use the release:publish event rather than looking at all tags
  # Only release events will trigger the publishing jobs
  release:
    types:
      - published

  # Allow manual triggering of the packaging jobs
  # This will not publish packages, but they will be available as workflow assets
  workflow_dispatch:


# Restrict workflow permissions
permissions:
  contents: read


# Use latest supported language versions for packaging jobs
env:
  JAVA_VERSION: "21"
  JAVA_DISTRIBUTION: "zulu"
  PYTHON_VERSION: "3.14"
  NODE_VERSION: "22"
  NPM_REGISTRY_URL: "https://registry.npmjs.org"


jobs:

  # Java publishing is managed through Gradle, which does both build and publish
  # There is no neat way to split the build / publish phases across jobs
  # So, include publish to Maven as a conditional step in the build job

  python_runtime_packages:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: PIP Upgrade
        run: python -m pip install --upgrade pip

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build environment dependencies
        run: |
          pip install -r tracdap-runtime/python/requirements.txt

      - name: Build runtime package
        env:
          TRAC_PYTHON_BUILD_ISOLATION: false
        run: python tracdap-runtime/python/build_runtime.py --target dist ext

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python_runtime_packages
          path: build/python/dist
          retention-days: 7

  web_api_package:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cd tracdap-api/packages/web
          npm ci

      - name: Set TRAC version
        run: |
          cd tracdap-api/packages/web
          npm run tracVersion:posix

      - name: Build API
        run: |
          cd tracdap-api/packages/web
          npm run buildApi

      - name: Create tarball
        run: |
          cd tracdap-api/packages/web
          mkdir dist
          cd dist
          npm pack ..

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web_api_package
          path: tracdap-api/packages/web/dist
          retention-days: 7

  publish_to_github:

    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    runs-on: ubuntu-latest

    needs:
      - python_runtime_packages
      - web_api_package

    # Permissions to upload artifacts
    permissions:
      contents: write

    steps:

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get TRAC version
        id: tracdap-version
        run: |
          tracdap_version=`dev/version.sh`
          echo "tracdap_version = ${tracdap_version}"
          echo "tracdap_version=${tracdap_version}" >> $GITHUB_OUTPUT

      - name: Fetch Python runtime package
        uses: actions/download-artifact@v4
        with:
          name: python_runtime_packages
          path: tracdap-api-packages-${{ steps.tracdap-version.outputs.tracdap_version }}/python_runtime_packages

      - name: Fetch web API package
        uses: actions/download-artifact@v4
        with:
          name: web_api_package
          path: tracdap-api-packages-${{ steps.tracdap-version.outputs.tracdap_version }}/web_api_package

      - name: Build API packages zip file
        run: zip -r tracdap-api-packages-${{ steps.tracdap-version.outputs.tracdap_version }}.zip tracdap-api-packages-${{ steps.tracdap-version.outputs.tracdap_version }}/

      - name: Publish plugins package
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $RELEASE_TAG tracdap-plugins-${{ steps.tracdap-version.outputs.tracdap_version }}.zip

      - name: Publish API packages
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $RELEASE_TAG tracdap-api-packages-${{ steps.tracdap-version.outputs.tracdap_version }}.zip

  publish_to_pypi:

    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    runs-on: ubuntu-latest

    needs:
      - python_runtime_packages

    # Permissions for OIDC auth with PyPI
    permissions:
      id-token: write

    steps:

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Fetch Python runtime package
        uses: actions/download-artifact@v4
        with:
          name: python_runtime_packages
          path: tracdap_python_dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tracdap_python_dist/

  publish_to_npm:

    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    runs-on: ubuntu-latest

    needs:
      - web_api_package

    # Permissions for OIDC auth with PyPI
    permissions:
      contents: read
      id-token: write

    steps:

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Update NPM
        run: npm install -g npm@latest && npm --version

      - name: Fetch web API package
        uses: actions/download-artifact@v4
        with:
          name: web_api_package
          path: tracdap_dist/

      - name: Get TRAC version
        id: tracdap-version
        run: |
          tracdap_version=`dev/version.sh`
          tracdap_tag=`dev/version_tag.sh ${tracdap_version}`
          echo "tracdap_version = ${tracdap_version}"
          echo "tracdap_tag = ${tracdap_tag}"
          echo "tracdap_tag=${tracdap_tag}" >> $GITHUB_OUTPUT

        # NPM publish wants a folder in NPM layout
        # So, extract the tarball and publish using the NPM package files
        # Also, add an entry in .npmrc to tell NPM to use an auth token from the environment
      - name: Publish to NPM
        env:
          NPM_TAG: ${{ steps.tracdap-version.outputs.tracdap_tag }}
        run: |
          tar -xzvf tracdap_dist/*
          cd package
          npm publish --access public --tag ${NPM_TAG}
